name: shop_easyy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  http: ^1.2.1
  shared_preferences: ^2.2.2
  fluttertoast: ^9.0.0
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  dio: ^5.4.3+1
  intl: ^0.20.2
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_auth: ^6.1.3
  flutter_local_notifications: ^19.5.0
  flutter_dotenv: ^6.0.0
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.png
