name: shop_easyy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  http: ^1.2.1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  dio: ^5.4.3+1
  intl: ^0.19.0
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  firebase_auth: ^5.3.4
  flutter_local_notifications: ^18.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.png
